<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Finds and removes local_aireader ad hoc task rows that have given up.
 *
 * @package    local_aireader
 * @copyright  2026 Saylor Academy
 * @license    https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace local_aireader\task;

use local_aireader\manager\asset_manager;

/**
 * Recovery for task rows left at zero remaining attempts.
 *
 * {@see failure_policy} stops new ones being created, but rows that ran out of
 * attempts under an older release are still sitting in `task_adhoc`, and they
 * are not inert. `get_next_adhoc_task()` skips them, so they never run again,
 * while `get_queued_adhoc_task_record()` still matches them by payload, so they
 * suppress every fresh queue attempt for the same asset. Until core's
 * four-week failed-task purge removes them, that narration cannot be
 * regenerated by a page view or by an admin pressing Regenerate.
 *
 * Deleting the row is the whole recovery, but "the work re-queues afterwards"
 * means two different things depending on the class, and it is worth being
 * exact because an earlier version of this file was not:
 *
 * - `generate_audio`: re-queued by `get_status` the next time anyone opens the
 *   page, because the asset is left in pending/stale/error, and immediately by
 *   an admin pressing Regenerate.
 * - `align_audio`: the asset is `ready`, so it used to be re-queued by nothing
 *   at all, alignment was only ever queued at the tail of a successful
 *   generation, and `get_status` does not re-queue ready assets. Since 1.8.3
 *   `get_status` also queues alignment for a ready asset that has no segments,
 *   so viewing the page is enough for these too. On an older release the only
 *   route was Regenerate, which re-pays for the whole narration.
 *
 * Clearing the rows also lifts the affected assets' retry cool-downs, so the
 * re-queue happens on the next page view rather than up to a day later.
 * Nothing else on the asset is touched and no stored audio is removed.
 * Reviving the task row instead (by resetting `attemptsavailable`) would simply
 * replay the same permanent failure and rebuild the same corpse.
 *
 * @package local_aireader
 */
class dead_task_cleaner {
    /** @var string Component whose rows this class is allowed to touch. */
    private const COMPONENT = 'local_aireader';

    /**
     * List the plugin's exhausted task rows, annotated with their asset.
     *
     * `timestarted IS NULL` excludes a task that is running right now. A row at
     * zero attempts can still be executing, because "Run now" and
     * `adhoc_task.php --id=N --force` deliberately bypass the attempts filter,
     * and deleting the row out from under that run would be a genuine race.
     * A failed run clears `timestarted` again, so the dead rows we want are
     * always included.
     *
     * @return \stdClass[] One entry per row: id, classname, assetid,
     *                     assetstatus (null when the asset is gone),
     *                     firststartingtime, faildelay.
     */
    public static function find_dead(): array {
        global $DB;

        $rows = $DB->get_records_select(
            'task_adhoc',
            'component = :component AND attemptsavailable = 0 AND timestarted IS NULL',
            ['component' => self::COMPONENT],
            'classname ASC, id ASC'
        );

        $out = [];
        foreach ($rows as $row) {
            // Decoded in PHP rather than with JSON_EXTRACT so this works the
            // same on PostgreSQL and MariaDB, which the plugin both support.
            $data = json_decode((string)$row->customdata, true);
            $assetid = is_array($data) ? (int)($data['assetid'] ?? 0) : 0;
            $asset = $assetid > 0 ? asset_manager::get_by_id($assetid) : null;
            $out[] = (object)[
                'id'                => (int)$row->id,
                'classname'         => (string)$row->classname,
                'assetid'           => $assetid,
                'assetstatus'       => $asset ? (string)$asset->status : null,
                'firststartingtime' => (int)($row->firststartingtime ?? 0),
                'faildelay'         => (int)($row->faildelay ?? 0),
            ];
        }
        return $out;
    }

    /**
     * Remove the exhausted rows, or just report them.
     *
     * Idempotent: a second run finds nothing, because the rows it would act on
     * are gone. Safe to run before or after the code fix ships.
     *
     * Also lifts the retry cool-down on the assets those rows named, so the
     * work they were blocking is picked up by the next page view instead of
     * waiting out a backoff that was set while the row was still in the way.
     * The failure counts are left alone, so the backoff resumes from where it
     * was if the work fails again.
     *
     * @param bool $dryrun True to report only and change nothing.
     * @return \stdClass[] The rows found, in the shape {@see find_dead()} returns.
     *                     Identical whether or not this was a dry run, so the
     *                     caller can print one list either way.
     */
    public static function clear(bool $dryrun): array {
        global $DB;

        $dead = self::find_dead();
        if ($dryrun || !$dead) {
            return $dead;
        }

        $ids = array_map(static function (\stdClass $row): int {
            return $row->id;
        }, $dead);
        [$insql, $params] = $DB->get_in_or_equal($ids, SQL_PARAMS_NAMED);
        $params['component'] = self::COMPONENT;
        // The component and attempts conditions are repeated in the DELETE
        // rather than trusting the id list, so a row that was picked up between
        // the read and the write can never be removed mid-run.
        $DB->delete_records_select(
            'task_adhoc',
            "id {$insql} AND component = :component AND attemptsavailable = 0 AND timestarted IS NULL",
            $params
        );

        asset_manager::clear_retry_cooldowns(array_map(static function (\stdClass $row): int {
            return $row->assetid;
        }, $dead));

        return $dead;
    }
}
